### ISSUE TITLE
Plugins Service / Uptime

### ISSUE THREAD

**Issue by headquaker** [OCSInventory-NG/Plugins#1]
Je n'ai pas les informations qui apparaissent dans OCS alors que pour Office c'est bon.
En local via une commande /local /xml /debug=2 j'ai bien les information.

**Comment by gillesdubois** [comment]
Bonjour,

J'ai ouvert votre issue sur le plugin correspondant : https://github.com/PluginsOCSInventory-NG/uptime/issues

Note : OCSInventory-NG/Plugins est un repo temporaire il sera surement supprimer d'ici peu, désolé si cela peut porter confusion.

**Comment by headquaker** [comment]
Oui j'ai déjà fait tout ça.

J'ai seulement winusers et le plug office qui fonctionnent.
