### ISSUE TITLE
Plugin API documentation

### ISSUE THREAD

**Issue by fgendorf** [OCSInventory-NG/Plugins#2]
HI, where I can find a documentation about OCS plugins API.
I'm trying to create a plugin with a function like duplicates, but I don't found any information about checkbox, adicional forms, etc

Thanks for you help

**Comment by gillesdubois** [comment]
Hi,

A documentation is on the way, this one will be available as soon as possible but the user-side documentation ("How to use ...") is a priority for us before the developper's one.
However you can still send us a mail at contact@ocsinventory-ng.org or ask your questions about this API on the IRC, i'll be glad to help you.

Regards,
Gilles Dubois.
